### ISSUE TITLE
Current PhpStorm EAP incompatibilties

### ISSUE THREAD

**Issue by ktomk** [krasa/FrameSwitcher#11]
Since the last cycle of EAP releases w/ PhpStorm I do see issues with the Frame Switcher plugin.

Visually the list of opened projects grows all the time even if I open a project in the current window (so only one project should be opened).

Switching to an open listed project that is not opened (any longer) gives Exceptions then.

PhpStorm details:

PhpStorm 2017.1 EAP
Build #PS-171.1834.12, built on December 22, 2016
PhpStorm EAP User
Expiration date: January 21, 2017
JRE: 1.8.0_112-release-b620 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by ktomk** [comment]
Such an exemplary exception:

~~~
null
java.lang.NullPointerException
	at krasa.frameswitcher.FocusUtils.requestFocus(FocusUtils.java:20)
	at krasa.frameswitcher.FrameSwitchAction$1.actionPerformed(FrameSwitchAction.java:103)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:208)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:224)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:893)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:883)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:877)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:202)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:809)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

**Comment by krasa** [comment]
Thanks for reporting it!

**Comment by ktomk** [comment]
Thanks for the quick fix. Works like a charm since days. Update was available promptly after fix.
